version: 0.2
phases:
  build:
    commands:
      - export BUCKET=lambdacfdemo
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
      #- aws cloudformation package --template-file sam.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
   # - sam.yaml
    - outputtemplate.yaml
    
    