AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demoonelambda
Resources:
  Lambdagithub:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./FunctionOne
      FunctionName: Lambdagithub
      Description: 'Lambda function for CD Demo Test'
      MemorySize: 128
      Timeout: 30
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
            
  HelloWorldGithub:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: qaTest
      Handler: qa-hello-world.lambda_handler
      Runtime: python3.6
      CodeUri: ./FunctionTwo
      FunctionName: HelloWorldGithub
      Description: 'Hello WOrld'
      
  ApiGatewayLambdaGithub:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: apigateway
      Handler: lambdafunctionthree.lambda_handler
      Runtime: python3.6
      FunctionName: ApiGatewayLambdaGithub
      CodeUri: ./FunctionThree
      Description: 'Hello WOrld'
