AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./FunctionOne
      FunctionName: CDDemoLambda
      Description: 'Lambda function for CD Demo Test'
      MemorySize: 128
      Timeout: 30
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
            
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: qaTest
      Handler: qa-hello-world.lambda_handler
      Runtime: python3.6
      CodeUri: ./FunctionTwo
      FunctionName: HelloWorld
      Description: 'Hello WOrld'
      
  ApiGatewayLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: apigateway
      Handler: lambdafunctionthree.lambda_handler
      Runtime: python3.6
      FunctionName: ApiGatewayLambda
      CodeUri: ./FunctionThree
      Description: 'Hello WOrld'